GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5efd8b8f5310d154dcb0f55b

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Charles",
    "subscribedToChannel": "REST server build"
}

###
DELETE http://localhost:3000/subscribers/5efd8b8f5310d154dcb0f55b

###
PATCH  http://localhost:3000/subscribers/5efd9189128d4557be07ba16
Content-Type: application/json

{
    "name": "New name"
}